version: '3'
services:
  catanie:
    ports:
    - "4200:4200"
    build:
      context: catanie
  catamel:
    restart: always
    ports:
    - "3001:3000"
    build:
      context: catamel
    depends_on:
    - mongodb
  mongodb:
    image: mongo:4.1.5
  nodered:
    build:
      context: nodered
    ports:
    - "1880:1880"
    extra_hosts:
     - "dmsc-kafka01:10.4.0.13"
     - "dmsc-kafka02:10.4.0.204"
     - "dmsc-kafka03:10.4.0.28"
     - "dmsc-kafka04:10.4.0.27"
     - "dmsc-kafka05:10.4.0.29"
     - "dmsc-kafka06:10.4.0.31"
