
services:
  backend:
#
#    original Image
#    image: ghcr.io/scicatproject/backend-next:v4.5.0
#    or our own image e.g. : I`
    image: backendnext
#
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./config/functionalAccounts.json:/home/node/app/functionalAccounts.json
    env_file:
      - ./config/.env
    labels:
      - traefik.http.routers.backend.rule=Host(`backend.localhost`)
    ports:
      - "7009:3000"
    healthcheck:
      test: wget --spider -Y off 'http://127.0.0.1:3000/api/v3/health'
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
